name: Java CI with Maven - Test and package  # Name of the workflow

on:                # Events that trigger the workflow
  pull_request:
    branches:      # Specify branches to run the workflow on pull requests
      - dev
jobs:              # Defines one or more jobs that will run in the workflow
  build:           # Job name
    runs-on: ubuntu-latest  # OS for the job (e.g., ubuntu-latest, windows-latest, macos-latest)

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '21'
      - run: mvn –B package
